#let openings = (
  ("DoS/ISRO Internship & Student Project Trainee Schemes", "⚠️", "IN", "https://www.isro.gov.in/InternshipAndProjects.html"),
  ("Visiting Student Research Program at KAUST", "⚠️", "IN", "https://admissions.kaust.edu.sa/study/internships"),
  ("Max Planck Institute for Informatics - PhD Applications", "⚠️", "PH", "https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/application/phd-applications?utm_source=chatgpt.com"),
  ("The International Max Planck Research School on Astrophysics at the Ludwig Maximilians University Munich", "2025-11-01", "PH", "https://www.imprs-astro.mpg.de/content/application?utm_source=chatgpt.com"),
  ("UC Berkeley's Physics Graduate Program", "2025-12-15", "PH", "https://physics.berkeley.edu/academic/graduate-degree/graduate-admissions?utm_source=chatgpt.com"),
  ("Arizona State University Physics PhD Admission", "2026-01-31", "PH", "https://physics.asu.edu/admissions/phd-admissions?utm_source=chatgpt.com"),
  ("John S. Foster, Jr. Postdoctoral Fellowship and the Harold Brown Postdoctoral Fellowship", "2025-11-08", "PD", "https://findajob.agu.org/job/8025462/john-s-foster-jr-postdoctoral-fellowship-and-the-harold-brown-postdoctoral-fellowship/"),
  ("Exoplanet Characterisation Predictions via Gravitational Microlensing: Competition Funded PhD Project", "⚠️", "PH", "https://www.findaphd.com/phds/project/exoplanet-characterisation-predictions-via-gravitational-microlensing/?p171628"),
  ("HRDG- Nehru Science Postdoctoral research Fellowship", "⚠️", "PD", "https://csirhrdg.res.in/Home/Index/1/Default/3419/55?s=08"),
  ("Maria de Maeztu Postdoctoral position in Gravitational Waves Astronomy at the ICCUB", "2025-11-30", "PD", "https://www.lisamission.org/maria-de-maeztu-postdoctoral-position-in-gravitational-waves-astronomy-at-the-iccub/"),
  ("Princeton University PhD Graduate School Programme", "2025-11-16", "PH", "https://gradschool.princeton.edu/admission-onboarding/prepare/deadlines-and-fees"),
  ("University of Chicago Graduate School Programme", "⚠️", "PH", "https://grad.uchicago.edu/admissions/apply/guidelines-and-deadlines/"),
  ("University of Texas at Austin Graduate School Programme", "⚠️", "PH", "https://students.gradschool.utexas.edu/portal/app"),
  ("University of Utah Graduate School Programme", "⚠️", "PH", "https://admissions.utah.edu/apply/graduate-students/"),
  ("The Cologne Graduate School of Ageing Research (CGA)", "2025-11-03", "PH", "https://application.ageing-grad-school.de"),
  ("Training as a Material Tester", "2025-12-30", "IN", "https://bewerbermanagement.net/jobposting/f98c4a12019eb449bdf373a5ccc2ff1c02b4fbaf0"),
  ("Doctoral positions available at the Graduate School Life Science Munich", "⚠️", "PH", "https://academicpositions.com/ad/lmu-munich/2025/upcoming-doctoral-positions-available-at-the-graduate-school-life-science-munich-as-of-september-2025/237347"),
  ("PhD positions at the Cologne Graduate School of Ageing Research", "2025-11-03", "PH", "https://academicpositions.com/ad/cologne-graduate-school-ageing-research-cga/2025/phd-positions-at-the-cologne-graduate-school-of-ageing-research/236229"),
  ("University of North Carolina at Chapel Hill PhD Programme", "2025-12-16", "PH", "https://gradschool.unc.edu/degree-programs/"),
  ("University of North Carolina at Charlotte PhD Programme", "2025-12-01", "PH", "https://gradadmissions.charlotte.edu/apply-now/application-requirements/#deadlines"),
  ("Louisiana State University PhD Programme", "⚠️", "PH", "https://www.lsu.edu/graduateschool/admissions/requirements-deadlines.php"),
  ("PhD Position - EPFL", "⚠️", "PH", "https://www.linkedin.com/posts/florian-schueder-318b02148_open-position-phd-student-activity-7356598175018680320-gW2R?utm_source=share&utm_medium=member_desktop&rcm=ACoAADc_xDABBm9oWnlmA0AAJye9s7W9iDd-frw"),
  ("Post Doctoral Position at Institute of Physical Chemistry, Polish Academy of Sciences", "2025-12-31", "PD", "https://bs4s.edu.pl/")
)